# Generated by Django 5.2.4 on 2025-08-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.CharField(blank=True, choices=[('medium', 'Medium'), ('hard', 'Hard'), ('low', 'Low')], default='low', null=True),
        ),
    ]
