# Generated by Django 5.2.4 on 2025-08-30 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_donation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.CharField(blank=True, choices=[('1', 'Low'), ('2', 'Medium'), ('3', 'Hard')], default='1', null=True),
        ),
    ]
