# Generated by Django 5.2.4 on 2025-08-26 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_task_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.CharField(blank=True, choices=[('hard', 'Hard'), ('medium', 'Medium'), ('low', 'Low')], default='low', null=True),
        ),
    ]
