# Generated by Django 5.2.4 on 2025-08-28 10:59

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_task_level_donate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donate',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='donate',
            name='did',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=10, max_length=20, prefix='uid', unique=True),
        ),
        migrations.AlterField(
            model_name='donate',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('pending', 'Pending'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.CharField(blank=True, choices=[('hard', 'Hard'), ('low', 'Low'), ('medium', 'Medium')], default='low', null=True),
        ),
    ]
