# Generated by Django 5.2.4 on 2025-08-28 11:10

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_donate_transaction_id_donate_did_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='did',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=10, max_length=20, prefix='did', unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.CharField(blank=True, choices=[('medium', 'Medium'), ('low', 'Low'), ('hard', 'Hard')], default='low', null=True),
        ),
    ]
