# Generated by Django 5.2.4 on 2025-08-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_donate_did_alter_task_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('hard', 'Hard'), ('medium', 'Medium')], default='low', null=True),
        ),
    ]
