# Generated by Django 5.2.4 on 2025-08-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_donate_status_alter_task_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='level',
            field=models.CharField(blank=True, choices=[('medium', 'Medium'), ('low', 'Low'), ('hard', 'Hard')], default='low', null=True),
        ),
    ]
