# Generated by Django 5.2.4 on 2025-08-31 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='profile/default.png', upload_to='profile/'),
        ),
    ]
